# 回帰分析 {#regression}


```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  include = TRUE
)
opts_knit$set(width = 100)
```


```{r}
library(tidyverse)
d_csv <- read_csv("data/example_7.csv")
d_csv
```


```{r}
library(car)
d <- d_csv %>%
  mutate(gender = factor(c1_1, 
                         levels = 1:2,
                         labels = c("Men","Women")),
         grade = 5 - c15a,
         asp = car::recode(c19, "1=9;2=12;3:5=14;6=16;7=18;else=NA"),
         medu = car::recode(m25m_b, "1:3=1;4:6=2;7:8=3;else=NA"),
         medu = factor(medu, 
                       levels = 1:3, 
                       labels = c("JH/HS","JC/PTC","Univ")),
         fedu = car::recode(m25f_b, "1:3=1;4:6=2;7:8=3;else=NA"),
         fedu = factor(fedu, 
                       levels = 1:3, 
                       labels = c("JH/HS","JC/PTC","Univ")),
  ) %>%
  select(id, gender, grade, asp, medu, fedu)
d
```

```{r}
fit_1 <- lm(asp ~ grade, data = d)
fit_1
summary(fit_1)
```

```{r}
fit_2 <- lm(asp ~ grade + gender, data = d)
fit_2
summary(fit_2)
```


```{r}
fit_3 <- lm(asp ~ grade + gender + medu + fedu, data = d)
fit_3
summary(fit_3)
```


```{r}
library(stargazer)
stargazer(fit_1, fit_2, fit_3, type = "text",
          no.space = TRUE)
```


サンプルサイズが揃っていない．


```{r}
library(estimatr)
```

